### ISSUE TITLE
Custom queries

### ISSUE THREAD

**Issue by u-abramchuk** [schubergphilis/sensu-plugins-prometheus-checks#4]
Hi,

I'm trying to pull custom metrics data (not from node-exporter, but from instrumented application) from Prometheus using sensu-plugins-prometheus-checks. Plugin is able to fetch data and execute checks but then fails on append_event method:
```
/var/lib/gems/2.3.0/gems/sensu-plugins-prometheus-checks-2.3.0/lib/sensu/plugins/prometheus/checks/runner.rb:234:in `sensu_safe': undefined method `gsub' for nil:NilClass (NoMethodError)
from /var/lib/gems/2.3.0/gems/sensu-plugins-prometheus-checks-2.3.0/lib/sensu/plugins/prometheus/checks/runner.rb:260:in `append_event'
from /var/lib/gems/2.3.0/gems/sensu-plugins-prometheus-checks-2.3.0/lib/sensu/plugins/prometheus/checks/runner.rb:153:in `block (2 levels) in evaluate_custom'
from /var/lib/gems/2.3.0/gems/sensu-plugins-prometheus-checks-2.3.0/lib/sensu/plugins/prometheus/checks/runner.rb:119:in `each'
from /var/lib/gems/2.3.0/gems/sensu-plugins-prometheus-checks-2.3.0/lib/sensu/plugins/prometheus/checks/runner.rb:119:in `block in evaluate_custom'
from /var/lib/gems/2.3.0/gems/sensu-plugins-prometheus-checks-2.3.0/lib/sensu/plugins/prometheus/checks/runner.rb:117:in `each'
from /var/lib/gems/2.3.0/gems/sensu-plugins-prometheus-checks-2.3.0/lib/sensu/plugins/prometheus/checks/runner.rb:117:in `evaluate_custom'
from /var/lib/gems/2.3.0/gems/sensu-plugins-prometheus-checks-2.3.0/lib/sensu/plugins/prometheus/checks/runner.rb:47:in `run'
from /etc/sensu/plugins/prometheus/check_prometheus.rb:16:in `<main>'
```

After some investigation it looks like plugin expects 'instance' field from response data to contain node's address, but as in my case metrics come from applicaton running in pod 'instance' contains pod's IP and port.

What is correct way to query metrics not from node-export (if supported at all)?

Thank you in advance.

**Comment by u-abramchuk** [comment]
I got it,

just needed to add label "app" in my application when collecting metrics.
